//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Supermarket.Views.Admin
{


        public partial class Customer
        {

                /// <summary>
                /// CusNameTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputText CusNameTb;

                /// <summary>
                /// CusEmailTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl CusEmailTb;

                /// <summary>
                /// CusPhoneTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputText CusPhoneTb;

                /// <summary>
                /// CusPasswordTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputText CusPasswordTb;

                /// <summary>
                /// ErrMsg control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label ErrMsg;

                /// <summary>
                /// EditBtn control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Button EditBtn;

                /// <summary>
                /// SaveBtn control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Button SaveBtn;

                /// <summary>
                /// DeleteBtn control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Button DeleteBtn;

                /// <summary>
                /// CustomerList control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.GridView CustomerList;
        }
}
