//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Supermarket.Views.Admin
{


        public partial class Suppliers
        {

                /// <summary>
                /// MNameTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputText MNameTb;

                /// <summary>
                /// ProdNumTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputText ProdNumTb;

                /// <summary>
                /// PlaceCb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.DropDownList PlaceCb;

                /// <summary>
                /// ErrMsg control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label ErrMsg;

                /// <summary>
                /// EditBtn control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Button EditBtn;

                /// <summary>
                /// SaveBtn control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Button SaveBtn;

                /// <summary>
                /// DeleteBtn control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Button DeleteBtn;

                /// <summary>
                /// ManufactList control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.GridView ManufactList;
        }
}
