//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Supermarket.Views.Admin
{


        public partial class Products
        {

                /// <summary>
                /// PNameTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputText PNameTb;

                /// <summary>
                /// PManufactCb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.DropDownList PManufactCb;

                /// <summary>
                /// PCateCb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.DropDownList PCateCb;

                /// <summary>
                /// PPriceTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputText PPriceTb;

                /// <summary>
                /// PQtyTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputText PQtyTb;

                /// <summary>
                /// ErrMsg control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label ErrMsg;

                /// <summary>
                /// EditBtn control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Button EditBtn;

                /// <summary>
                /// SaveBtn control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Button SaveBtn;

                /// <summary>
                /// DeleteBtn control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Button DeleteBtn;

                /// <summary>
                /// ProductList control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.GridView ProductList;
        }
}
