//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Supermarket.Views.Customer
{


        public partial class Billing
        {

                /// <summary>
                /// PNameTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputText PNameTb;

                /// <summary>
                /// PriceTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputText PriceTb;

                /// <summary>
                /// QtyTb control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.HtmlControls.HtmlInputText QtyTb;

                /// <summary>
                /// AddToBillBtn control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Button AddToBillBtn;

                /// <summary>
                /// ProductList control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.GridView ProductList;

                /// <summary>
                /// ShoppingCartList control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.GridView ShoppingCartList;

                /// <summary>
                /// PrintBtn control.
                /// </summary>
                /// <remarks>
                /// Auto-generated field.
                /// To modify move field declaration from designer file to code-behind file.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Button PrintBtn;
        }
}
